# data_synth.py
### notebook demo of data_synth module functions:
* r_df = data_synth. **get_rand_dataframe** (n_rows, n_cols, row_name_chars=5, col_name_chars=8)
* nw = data_synth. **get_nodes_from_spreadsheet** (adj_mat)
* spreadsheet_mat = data_synth. **get_clustered_spreadsheet** (n_clusters, cluster_width, row_multiplier=1)




In [1]:
# Link lifted from above: [home](https://dlanier.github.io/keg_notebooks/)  :format correct but wrong address

import os
import sys
import numpy as np
sys.path.insert(1, '../src')
import data_synth as ds

def append_dictionary_file(full_file, run_pars):

    """ Append or create a log file using yaml compatible format """

In [4]:
full_file = os.path.join('/Users/lanier4/dlanier_KnowEnG/tmp_Trash', 'junk_test.yml')
print(full_file)
run_pars = {'rinky':'dinky'}
writ_status = ds.append_dictionary_file(full_file, run_pars)
run_pars = {'parley':'vu'}
writ_status = ds.append_dictionary_file(full_file, run_pars)

/Users/lanier4/dlanier_KnowEnG/tmp_Trash/junk_test.yml


def base_coef_arr(big_n, bas, arr_len):

    """ convert an integer to an array of position multipliers in input base
    Args:
        big_n: an integer
        bas: the base to convert it to
        arr_len: pad the output with zeros to make it this length
    Returns:
        base_coef_arr: array of integers input integer in new base
    """

In [5]:
base_coef_arr = ds.base_coef_arr(big_n=57, bas=2, arr_len=3)
base_coef_arr

array([0, 0, 1])

def get_character_seq(bas_arr, caps=True):

    """ get a random sequence of characters
    Args:
        bas_arr: array of numbers in range 0, 25
        caps:  use Capital letters ? True or False
    Returns:
        char_arr
    """

In [10]:
char_arr = ds.get_character_seq(bas_arr=np.array([23,5,7,0]), caps=True)
char_arr

'XFHA'

def get_rand_unique_name_list(n_names, name_length):

    """ get a list of unique random names with same number of characters (dog-slow if n_names >100k)
    Args:
        n_names: number of unique names in the output
        name_length: number of characters in each name
    Returns:
        rand_uniq_name_list: list of names
    """

In [12]:
rand_uniq_name_list = ds.get_rand_unique_name_list(n_names=5, name_length=12)
rand_uniq_name_list

['LVEQQZNHWGHS',
 'YRAPLXLEBZYE',
 'NRRDYCANGMIA',
 'FAYZYXIGSZWU',
 'JKYSURZOUGKI']

def get_random_clusters(ncols, number_of_clusters=3):

    """ get a random set of clusters and construct an encoding matrix from those

    Args:
        ncols: number of columns
        number_of_clusters: number of rows

    Returns:
        H: encoding of the cluster number array
        C: cluster number array
    """

In [15]:
H, C = ds.get_random_clusters(ncols=12, number_of_clusters=3)
print(H, '\n\n', C)

[[ 1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.  0.  1.  1.  0.  1.  0.  0.]] 

 [0 0 2 1 2 0 2 2 1 2 0 1]


def symmetric_random_adjacency_matrix(network_dim, pct_nodes=0.3):

    """ symmetric random adjacency matrix from random set of nodes
    Args:
        network_dim: number of rows and columns in the symmetric output matrix
        pct_nodes: number of connections (nodes) as a function of network size.
    Returns:
        network: a symmetric adjacency matrix (0 or 1 in network_dim x network_dim matrix)
    """

In [16]:
network = ds.symmetric_random_adjacency_matrix(network_dim=5, pct_nodes=0.3)
network

array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.]])

def adjacency_matrix_to_node_set(N):

    """ create a network of nodes with edges from an adjacency matrix """

In [17]:
Node_set = ds.adjacency_matrix_to_node_set(network)
Node_set

array([[0, 2, 1],
       [1, 3, 1],
       [2, 4, 1],
       [3, 4, 1]])

def node_set_to_adj_mat(node_set):

    """ create and adjacency matrix from a network of nodes with edges """

In [18]:
network_bak = ds.node_set_to_adj_mat(Node_set)
network_bak

array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.]])

def get_clustered_spreadsheet(n_clusters, cluster_width, nrows):

    """ synthetic spreadsheet data with n_clusters (2 : 7) of n_clusters * cluster_width samplse """

In [3]:
spreadsheet_mat = ds.get_clustered_spreadsheet(n_clusters=3, cluster_width=3, nrows=12)
spreadsheet_mat

array([[ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.]])

In [4]:
#                              get_clustered_spreadsheet needs redefinition of inputs

def get_nodes_from_spreadsheet(SSArr):

    """ get the .edge set from a spreadsheet """

In [5]:
node_set_2 = ds.get_nodes_from_spreadsheet(spreadsheet_mat)
node_set_2

array([[ 0,  1,  1],
       [ 0,  2,  1],
       [ 0,  3,  1],
       [ 1,  2,  1],
       [ 1,  3,  1],
       [ 2,  3,  1],
       [ 3,  4,  1],
       [ 3,  5,  1],
       [ 3,  6,  1],
       [ 3,  7,  1],
       [ 4,  5,  1],
       [ 4,  6,  1],
       [ 4,  7,  1],
       [ 5,  6,  1],
       [ 5,  7,  1],
       [ 6,  8,  1],
       [ 6,  9,  1],
       [ 6, 10,  1],
       [ 6, 11,  1],
       [ 7,  8,  1],
       [ 7,  9,  1],
       [ 7, 10,  1],
       [ 7, 11,  1],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

def get_rand_dataframe(n_rows, n_cols, row_name_chars=5, col_name_chars=8):

    """ get a radom number dataframe for test or whatever """

In [6]:
ran_df = ds.get_rand_dataframe(n_rows=12, n_cols=5, row_name_chars=5, col_name_chars=8)
ran_df

LBAZBNKY  KOVHRMAM  KTMQBHZC  ESQEJTWE  DIHHCUBK
UKAFF  0.468275  0.158010  0.247391  0.086890  0.197224
NFIYC  0.618764  0.250177  0.758779  0.129007  0.510853
QDLUL  0.222740  0.224529  0.164515  0.951284  0.307150
PUXYV  0.616959  0.578258  0.318280  0.198296  0.542738
ZPYDE  0.968946  0.679309  0.107965  0.144245  0.482047
NJAOS  0.756333  0.378778  0.705876  0.280156  0.388149
CWDPE  0.207702  0.065338  0.668899  0.633714  0.642047
WIRUP  0.641219  0.193301  0.026592  0.567361  0.715241
SXXKY  0.614207  0.177891  0.839989  0.248416  0.692268
CDWAC  0.949421  0.045724  0.481480  0.789135  0.333737
KLSJJ  0.287849  0.840916  0.384659  0.200210  0.646236
UQWQD  0.388293  0.763647  0.106070  0.482842  0.510429

def get_test_paramters_dictionary():

    """ universal dctionary of run parameters """

In [7]:
run_parameters = ds.get_test_paramters_dictionary()

for k in sorted(run_parameters.keys()):
    print(k, '\t\t', run_parameters[k])

cols_sampling_fraction 		 0.8
display_clusters 		 0
gg_network_name_full_path 		 ./run_dir/input_data/final_clean_4col.edge
method 		 cc_net_cluster_nmf
method_1 		 cluster_nmf
method_2 		 cc_cluster_nmf
method_3 		 net_cluster_nmf
method_4 		 cc_net_cluster_nmf
nmf_conv_check_freq 		 50
nmf_max_invariance 		 200
nmf_max_iterations 		 10000
nmf_penalty_parameter 		 1400
number_of_bootstraps 		 5
number_of_clusters 		 3
results_directory 		 ./run_dir/results
rows_sampling_fraction 		 0.8
rwr_convergence_tolerence 		 0.0001
rwr_max_iterations 		 100
rwr_restart_probability 		 0.7
spreadsheet_name_full_path 		 ./run_dir/input_data/final_clean_full_matrix.df
tmp_directory 		 ./run_dir/tmp
use_parallel_processing 		 0
