In [1]:
import os
import sys
import numpy as np
#                     \!/     Note relative local path to data_synth.py module here
sys.path.insert(1, '../src')
import data_synth as ds

# data_synth.py   --   notebook demo of data_synth module functions:

* r_df = data_synth. **get_rand_dataframe** (n_rows, n_cols, row_name_chars=5, col_name_chars=8)
* nw = data_synth. **get_nodes_from_spreadsheet** (adj_mat)
* spreadsheet_mat = data_synth. **get_clustered_spreadsheet** (n_clusters, cluster_width, row_multiplier=1)
* **node_set_to_adj_mat** (node_set)

In [7]:
ran_df = ds.get_rand_dataframe(n_rows=12, n_cols=5, row_name_chars=5, col_name_chars=8)
ran_df

FSZKGTTS  XRVPYUYT  MZEDSGTF  VRPLXFWH  VZASRTYN
GNQRK  0.688186  0.891568  0.622043  0.933769  0.303421
FOFUD  0.310129  0.154152  0.940825  0.428457  0.981142
UBFCQ  0.259829  0.978734  0.828126  0.259925  0.840683
HZRCE  0.137648  0.523366  0.190724  0.834988  0.188678
KRIQC  0.172895  0.701869  0.255003  0.706506  0.677475
QGOJP  0.279359  0.499722  0.830834  0.377990  0.476512
KJPPJ  0.537493  0.295409  0.819021  0.666839  0.405335
YAZZW  0.049948  0.665570  0.475085  0.161119  0.832102
GWYQQ  0.731122  0.515208  0.150900  0.844573  0.690910
XUPBL  0.950923  0.437826  0.798231  0.529648  0.685487
KVQIE  0.059817  0.201041  0.573329  0.076114  0.680559
TQKHR  0.771358  0.354958  0.502764  0.035081  0.701730

In [2]:
rand_names = ds.get_rand_unique_name_list(n_names=5, name_length=5)
rand_names

['KVUOY', 'WOAIE', 'LDILB', 'KYCRL', 'UUEUU']

In [8]:
#                                                           2 do: debug - values lost, zeros left over
node_set = ds.get_nodes_from_spreadsheet(ran_df.as_matrix())
node_set

array([[ 0,  1,  1],
       [ 0,  2,  1],
       [ 0,  3,  1],
       [ 0,  4,  1],
       [ 0,  5,  1],
       [ 0,  6,  1],
       [ 0,  7,  1],
       [ 0,  8,  1],
       [ 0,  9,  1],
       [ 0, 10,  1],
       [ 0, 11,  1],
       [ 1,  2,  1],
       [ 1,  3,  1],
       [ 1,  4,  1],
       [ 1,  5,  1],
       [ 1,  6,  1],
       [ 1,  7,  1],
       [ 1,  8,  1],
       [ 1,  9,  1],
       [ 1, 10,  1],
       [ 1, 11,  1],
       [ 2,  3,  1],
       [ 2,  4,  1],
       [ 2,  5,  1],
       [ 2,  6,  1],
       [ 2,  7,  1],
       [ 2,  8,  1],
       [ 2,  9,  1],
       [ 2, 10,  1],
       [ 2, 11,  1],
       [ 3,  4,  1],
       [ 3,  5,  1],
       [ 3,  6,  1],
       [ 3,  7,  1],
       [ 3,  8,  1],
       [ 3,  9,  1],
       [ 3, 10,  1],
       [ 3, 11,  1],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  

In [9]:
network_bak = ds.node_set_to_adj_mat(node_set)
network_bak

array([[ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [4]:
# 2 do get_clustered_spreadsheet needs redefinition of inputs -- not clear how many rows & cols
# 2 do randomization function: shuffle row-columns, randomize values
spreadsheet_mat = ds.get_clustered_spreadsheet(n_clusters=3, cluster_width=3, nrows=12)
spreadsheet_mat

array([[ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.]])

def append_dictionary_file(full_file, run_pars):

    """ Append or create a log file using yaml compatible format """

In [ ]:
full_file = os.path.join('/Users/lanier4/dlanier_KnowEnG/tmp_Trash', 'junk_test.yml')
print(full_file)
run_pars = {'rinky':'dinky'}
writ_status = ds.append_dictionary_file(full_file, run_pars)
run_pars = {'parley':'vu'}
writ_status = ds.append_dictionary_file(full_file, run_pars)

def base_coef_arr(big_n, bas, arr_len):

    """ convert an integer to an array of position multipliers in input base
    Args:
        big_n: an integer
        bas: the base to convert it to
        arr_len: pad the output with zeros to make it this length
    Returns:
        base_coef_arr: array of integers input integer in new base
    """

In [ ]:
base_coef_arr = ds.base_coef_arr(big_n=57, bas=2, arr_len=3)
base_coef_arr

def get_character_seq(bas_arr, caps=True):

    """ get a random sequence of characters
    Args:
        bas_arr: array of numbers in range 0, 25
        caps:  use Capital letters ? True or False
    Returns:
        char_arr
    """

In [ ]:
char_arr = ds.get_character_seq(bas_arr=np.array([23,5,7,0]), caps=True)
char_arr

def get_rand_unique_name_list(n_names, name_length):

    """ get a list of unique random names with same number of characters (dog-slow if n_names >100k)
    Args:
        n_names: number of unique names in the output
        name_length: number of characters in each name
    Returns:
        rand_uniq_name_list: list of names
    """

In [ ]:
rand_uniq_name_list = ds.get_rand_unique_name_list(n_names=5, name_length=12)
rand_uniq_name_list

def get_random_clusters(ncols, number_of_clusters=3):

    """ get a random set of clusters and construct an encoding matrix from those

    Args:
        ncols: number of columns
        number_of_clusters: number of rows

    Returns:
        H: encoding of the cluster number array
        C: cluster number array
    """

In [12]:
H, C = ds.get_random_clusters(ncols=12, number_of_clusters=3)
print(H, '\n\n', C)

[[ 1.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  1.]
 [ 0.  1.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  1.  0.  1.  1.  0.  0.  1.  0.]] 

 [0 1 2 1 2 0 2 2 0 1 2 0]


def symmetric_random_adjacency_matrix(network_dim, pct_nodes=0.3):

    """ symmetric random adjacency matrix from random set of nodes
    Args:
        network_dim: number of rows and columns in the symmetric output matrix
        pct_nodes: number of connections (nodes) as a function of network size.
    Returns:
        network: a symmetric adjacency matrix (0 or 1 in network_dim x network_dim matrix)
    """

In [10]:
network = ds.symmetric_random_adjacency_matrix(network_dim=5, pct_nodes=0.3)
network

array([[ 0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.]])

def adjacency_matrix_to_node_set(N):

    """ create a network of nodes with edges from an adjacency matrix """

In [11]:
Node_set = ds.adjacency_matrix_to_node_set(network)
Node_set

array([[0, 2, 1],
       [0, 3, 1],
       [1, 3, 1],
       [2, 3, 1],
       [2, 4, 1],
       [3, 4, 1]])

### run parameters synthesis
**def get_test_paramters_dictionary():**

    """ universal dctionary of run parameters """

In [ ]:
run_parameters = ds.get_test_paramters_dictionary()

for k in sorted(run_parameters.keys()):
    print(k, '\t\t', run_parameters[k])