In [1]:
import os
import sys
import time

import numpy as np
import pandas as pd

import data_synth as ds

## Mark Me Down Scotty
* a cell to test the markdown
* possibly for dakine documentation

In [2]:
#                    symmetric_random_adjacency_matrix      : get a random network matrix
network_dim = 5
pct_nodes = 0.3
network = ds.symmetric_random_adjacency_matrix(network_dim, pct_nodes)
print('network\n{}'.format(network))

network
[[ 0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  1.]
 [ 0.  0.  0.  1.  0.]]


In [3]:
node_set = ds.adjacency_matrix_to_node_set(network)
print('node_set\n{}'.format(node_set))

adj_mat = ds.node_set_to_adj_mat(node_set)
print('adj_mat\n{}'.format(adj_mat))

node_set
[[0 1 1]
 [0 3 1]
 [1 2 1]
 [2 3 1]
 [3 4 1]]
adj_mat
[[ 0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  1.]
 [ 0.  0.  0.  1.  0.]]


In [4]:
#                       get_random_clusters         :    set of clusters and as encoding matrix and cluster numbers
ncols = 5
number_of_clusters = 3
H, C = ds.get_random_clusters(ncols, number_of_clusters)
print('H matrix:\n{}\t\nClustering:\n{}'.format(H, C))

H matrix:
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  1.]]	
Clustering:
[2 1 2 1 2]


In [5]:
#                      get_rand_unique_name_list        :   unordered (sortable) list of unique names for labels
n_names = 5
name_length = 7
rand_uniq_name_list = ds.get_rand_unique_name_list(n_names, name_length)
print('rand_uniq_name_list:')
for nombre in sorted(rand_uniq_name_list):
    print(nombre)

rand_uniq_name_list:
DEBKSUK
GVWMDOK
KVTBDNI
WYGUVBO
ZDHJAOB


In [6]:
#                                 get_character_seq   : convert an array of numbers to a char array
bas_arr = np.array([2,6,9,7,0])
caps = True
char_arr = ds.get_character_seq(bas_arr, caps)
print(char_arr)
list(char_arr)

CGJHA


['C', 'G', 'J', 'H', 'A']